### ISSUE TITLE
Wrong link Bundestags

### ISSUE THREAD

**Issue by patschw** [texttechnologylab/GerParCor#4]
Hey guys,

thank you for compiling this amazing corpus! When trying to download the Bundestags files it takes me to this link, which does not work: http://gerparcor.texttechnologylab.org/data/Bundestat.gar 

When manually changing to this, it works: http://gerparcor.texttechnologylab.org/data/Bundestag.tar

Best

Patrick

**Comment by abrami** [comment]
Done.
